DROP TABLE IF EXISTS EMPLOYEE;
CREATE TABLE EMPLOYEE (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
first_name VARCHAR(50) NOT NULL,
last_name VARCHAR(100) NOT NULL,
email_address VARCHAR(50) NOT NULL
);